### PR TITLE
added store banner and moved svg icon to store folder

### PR DESCRIPTION
**Pull request by moWerk**

### CODE REVIEW

**Comment by zwieberl** [comment]
Sorry for the delay. Thanks for the very quick new pullrequest!

Quick question up front: What are the svg-files for? My viewer shows for the icon only the border of icon, the rest is empty. For the svg-banner: It also looks completely different than the jpg and png-version. Not quite sure what to make of them.

On to the banner itself (jpg/png-version): 
I definitely like the background! Very nice variation of the icon, but different enough to get more emphasis on the "feedsymbol-like" shape of the scales. Well done!

The text font, I'm not so sure of ;-) It has this kind of retro-, old-arcade-games-style to it. 
It might only be the color (which definitely has to change, otherwise my wife will kill me :-D ), but I suspect its the font itself as well. 

I'm not that good with fonts. The standard Sailfish-font might integrate nicely with the store, but is probably a bit boring. 
Maybe something more resembling handwriting?

**Comment by moWerk** [comment]
chr chr. Yes you got it right.
I abonndoned my TV and refrain to watch most of what mediatheks offer since ~1998.
So using them at all is completely retro to me and i just had to slap a 90s Boombox/Commander Keen style on it :)
Don't worry, the most work was with the background. So, good you like it.
Already tried some script fonts but they all get lost on the vivid background, hence the added bright green to even set the giant boombox font apart properly.
Will do some experimenting during the next few days.

Yeah, i just realized my inkscape is messing up the svgs... Thanks for pointing it out, i did not check since my workflow was flawless on last project i did 6 month ago...
The pngs are all exports from the supplied svg using inkscape. So the objects/layers are all contained in the file. Only the order seems to be broken and only the top most layer is shown when viewing them outside inkscape...
Could you help me out and try to open them not in browser or imageviewer but inkscape supplied with your distro? My inkscape is 0.92.2 2405546. Would be good to know if other inkscape versions or even installs of the same version give different representation of the svgs built by my version. Have not found a mention of such bug online when i searched just now. Maybe i need to downgrade to earlier version of inkscape or reinstall.
So if you got a different inkscape ver with your distro and the svg look different to the pngs i would try that inkscape and rebuild the svgs in there.

**Comment by zwieberl** [comment]
Works with both
Inkscape 0.92.2
Inkscape 0.92.3

**Comment by zwieberl** [comment]
Addendum:
Does not work for Inkscape 0.48.5

**Comment by moWerk** [comment]
Ok, i found out the svgs i based the work on are messed up somehow. If i start new all is ok.
Will rework the svgs but first some variations on the old messed base just to narrow down on the font.
I hope one of them is close to your liking. Frankly i already put more time in this than i should have :)

storebanner_pecita1
storebanner_dragon1
storebanner_variete1
storebanner_oleo1
storebanner_lobster1
storebanner_segoe2

**Comment by zwieberl** [comment]
Oh man, this was tough! Really tough! They are all excellent, I'm still not sure if my decision is "the right one" :-)

I think I will go for the second to last one (number 5).

> Frankly i already put more time in this than i should have 

If it makes you feel any better: Me too :-) (Meaning the App itself)
No, seriously, you did a fantastic job. Thank you very very much, indeed!

With what name would you like to be mentioned in the upcoming Abouts-Page? (Maybe a URL to link to as well?)

**Comment by moWerk** [comment]
Great! The font is called Lobster and free to use.
You would need to give credits in your github or app somewhere like:

The font "Lobster" is licensed under SIL Open Font License and was created by [Impallari Type](http://www.impallari.com/lobster). [license](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)

For me it is "eLtMosen" or "mosen" on CC-BY-3.0 license.

We could have a Logo at app startup too if we further thin out the banner or only take the Lobster typed logo. Lobster pairs very well with SourceSans, the Jolla font.

**Comment by zwieberl** [comment]
Will do!

I thougt you already spent too much time on this, and now you want to do another one? :-D
Today I experimented with a Cover picture and simply used the icon with only 25% opacity. I thought it looked quite nice.

**Comment by zwieberl** [comment]
I just now submitted a new version to harbour, including icon and using the png-Banner provided above (will probably be published on Monday).

Would be good, if you could update the pull-request to include the new banner (svg), so I can merge.
Alternatively, I could just copy the png and commit myself without the svg. As you like and as your time allows.

Either way: Thank you very much for your hard work on this!

**Comment by moWerk** [comment]
Cool!
Nothing to thank for, really. I just take every possibility to make the Jolla store look nice :)
My wining has nothing to do with fishtheke. Sorry for dropping the sour comment about my spent time. I was and am just really upset by the svg thingy failing on me. I am literally doing hobbyist computer graphics since 25 years and feel like a noob handling that error.
Which would have happened with any recent svg related work i would have done i guess. sooooo. Again thank you for the opportunity to repair my workflow. lol.
I am still not sure what happens at all. My attempts to recreate the banner or icon in a new file by coping over layers or even juggling svg code snippets always fails. As soon as i use any code from the messed files, it messes up the new file. I tried running parts of the code through svg minifier and optimizer scripts with now apparent luck. Saved in all available file formats to maybe convert them back with better results. no luck. Only inkscape represents the vectors, filters and layers correctly and can correctly export to png, pdf and all pixel representations i tried.
So bare with me. I am on it but can not promise any ETA. Currently i plan to draw all shapes again, save step by step and see when it possibly breaks to maybe shift the fault to inkscape and have a basis for a bug report over there.
Cheers and have a nice sunday!

**Comment by moWerk** [comment]
I made progress \o/
The problem was an already report inkscape bug with gradients. The storeBanner is already fixed. Now looking for more time to rework the icon.

**Comment by moWerk** [comment]
Oh nooo... i do not get it.
Now all is displaying nicely in some viewers i checked and it still misses objects in githubs view...
Going to try some more next week.

**Comment by zwieberl** [comment]
I feel you :-D 
Sometimes everything goes up in flames

**Comment by moWerk** [comment]
Hmmm. So the files are displayed differently in browsers.
Firefox and Midori miss objects.
All is fine in Chrome(ium) and Opera. wtf...

**Comment by zwieberl** [comment]
Confirmed. My Firefox has missing objects as well. 
But that might be a bug in the svg-lib firefox is using?

**Comment by jgibbon** [comment]
It works when leaving out the filter… which for me has no visible effect anyway. :)

Like this: [harbour-fishtheke.svg.txt](https://github.com/zwieberl/harbour-fishtheke/files/2734100/harbour-fishtheke.svg.txt) – I have also removed some stroke widths while trying things, those may have been wanted.

cheers!

**Comment by moWerk** [comment]
Thanks Velox!
That was the solution. The filters where set multiple times and as you correctly observed, even had no visual effect... The only filter left now is the fonts shadow.

@zwieberl 
I added the logofont as promised, maybe you can play around with it a little and find a use. I would suggest to have it on the "About" page and maybe even on the startpage above the sort and order fields?
Maybe it also looks good in the Task/Cover to replace the current Fishtheke in SourceSans font.

Further more i am kind of missing a play button now that you have built in all those great options.
My idea was to have a playbutton already in the Listview? Like have a small blue playbutton in each row so one does not have to go deeper but start to play with (maybe last used play-method by user or easiest to implement or most reliable) method directly from the list view? The orange visted/play button could indicate which stream you already watched.
That might need some more work on your side to track the viewed streams i guess.

**Comment by zwieberl** [comment]
Thanks for this!

Regarding logofont: Yes, I will play around where it looks good. Might be nice to have it in Cover and About - Page above/below the icon.  
In the startpage we will see. Its getting a bit crowded there ;-) (see below)

Regarding "play - button in the ListView": To be honest: I don't think I'm going to do that, for various reasons. First, its a lot of work ;-). Second, the devils in the details. They all have different links available, so simply "choosing the last selected type" isn't going to work (some have HD and SD-links, others only one stream-link without anything, others again only a webpage). 
And last but not least: I'm not sure anybody needs that. I mean: is anybody really binge-watching Mediatheken, to need a quick-play? I'd rather put the little time I have into DownloadManager and more sources (such as archive.org, which I started multiple times and stashed it again over and over. This will add more options to startpage, so not sure if logofont can fit there anymore.). 

I might however play around with the play-icons you created. Could be a nice addition to the Details-page (orange for direct links, blue for webpage or something like that.)

Either way, thank you again for your hard work with the icons! They are very much appreciated.

**Comment by moWerk** [comment]
I share your concerns regarding (too) much work on the ListView, thanks for explaining.
If from your placement testing an idea arises how to refine any of the SVGs, let me know.
And congratulations on the quick overall advancement of fishtheke. Very impressive.

**Pull request merged**
