### PR TITLE
designed a unique icon, added pngs and svg master

### PR DESCRIPTION
**Pull request by moWerk**
If you like it already just take it as it is under CC-BY-3.0
Else i am perfectly happy with some discussion where to head.
Currently the scales should resemble the multitude of streams/broadcasts you can choose with the app.
Greetings, mosen

### CODE REVIEW

**Comment by zwieberl** [comment]
Hi. 
Thanks for this! I like it. 
One small idea: Could you make maybe 1/3 - 1/2 of the scales "different"? Maybe invert colors or just a shade darker/brighter to add a bit of contrast. Don't know how easy or hard that is. I also don't know if this is going to look good or not, so if its too much of a hassle, don't do it ;-)

**Comment by moWerk** [comment]
Yep, i was thinking along the lines but honestly i followed the rule "less is more" and drew the line at the current proposal ;) Will look into either making the scales in different shades/colors or somehow else make them more visible.
Only it might take some days as i am heading for work related travel.

**Comment by zwieberl** [comment]
Great! Thanks. No worries about the delay, its fine "whenever" :-)

**Comment by zwieberl** [comment]
Just a quick follow-up idea: "Some scales different" might look a bit chaotic. It could also be interesting to only have one scale "very different". Sort of to express the idea of the app "to find among all those feeds the one you are looking for". What do you think?

**Comment by moWerk** [comment]
HaHa, i worked on exactly that approach ^^

First i enlarged the scales so they are better visible and give a nicer pattern.
The scales got a gradient from blue to greenish for some depths.
The bright blue border got a dropshadow to give it some contrast and depths.
Then i tried some variations which scale to give a unique color.

Here some steps on the way to discuss further:
[fishtheke.zip](https://github.com/zwieberl/harbour-fishtheke/files/2662873/fishtheke.zip)


fishtheke5_128
fishtheke6_128
fishtheke7_128
fishtheke8_128
fishtheke9_128
fishtheke10_128

**Comment by zwieberl** [comment]
Great minds think alike :-D 
I like the orange one in the upper left corner a lot (4. picture)!

**Comment by zwieberl** [comment]
You are awesome! Thank you very much, indeed!

**Comment by moWerk** [comment]
Happy to be of help :)
What about a banner for Jolla Store? Do you have any kind of "slogan" or key sentence like "The mediathek browser for Sailfish OS" or alike?

**Comment by zwieberl** [comment]
Banner would of course also be nice. 
No, I don't have a slogan (yet). 
I am currently working on adding more sources, not only mediathek (e.g. archive.org). But not sure if I get this to work :)

**Pull request merged**
